### ISSUE TITLE
Failed to fetch localhost manifest

### ISSUE THREAD

**Issue by sagarspatil** [openai/plugins-quickstart#11]
I am getting this error:
**Failed to fetch localhost manifest. Check to ensure your localhost is running and your localhost server has CORS enabled.**

I checked and can see the manifest file at http://localhost:5003/.well-known/ai-plugin.json

Any idea what might be wrong here?

Log:
 * Serving Quart app 'main'
 * Environment: production
 * Please use an ASGI server (e.g. Hypercorn) directly in production
 * Debug mode: True
 * Running on http://0.0.0.0:5003 (CTRL + C to quit)
[2023-04-19 18:44:54 +0200] [20687] [INFO] Running on http://0.0.0.0:5003 (CTRL + C to quit)

**Comment by saschaschramm** [comment]
> I am getting this error: **Failed to fetch localhost manifest. Check to ensure your localhost is running and your localhost server has CORS enabled.**
> 
> I checked and can see the manifest file at http://localhost:5003/.well-known/ai-plugin.json
> 
> Any idea what might be wrong here?
> 
> Log:
> 
> * Serving Quart app 'main'
> * Environment: production
> * Please use an ASGI server (e.g. Hypercorn) directly in production
> * Debug mode: True
> * Running on http://0.0.0.0:5003 (CTRL + C to quit)
>   [2023-04-19 18:44:54 +0200] [20687] [INFO] Running on http://0.0.0.0:5003 (CTRL + C to quit)

I consistently encounter the same error when attempting to install the plugin in Safari. However, when I switch to Chrome, the installation proceeds successfully.

**Comment by chrisalbon** [comment]
Similar to @saschaschramm, I get the same error in Safari, but it works in Chrome.

**Comment by nhaskins** [comment]
I had this issue in Brave browser, so put the shields down, and it started working.

**Comment by seiyamiyaoka** [comment]
I had same error. It worked fine after changing the chrome settings.
```
Respect the result of Private Network Access preflights => default to disabled
```

**Comment by tddschn** [comment]
Any idea how to get localhost plugins work in Safari / WebKit based browsers?

**Comment by areibman** [comment]
Doesn't work on Chrome or Safari for me

**Comment by Klingefjord** [comment]
Get the same error on Chrome / Arc / Brave

**Comment by Doujiang2333** [comment]
from flask_cors import CORS

app = Flask(__name__)
# CORS(app, origins='https://chat.openai.com/')
CORS(app, origins='*')

**Comment by KristyleM** [comment]
Maybe your ai-plugin.json file is not a valid json.

**Comment by sagarspatil** [comment]
You need to enable cors for localhost and chat.openai.com
