### ISSUE TITLE
`Couldn't find manifest` error after following README

### ISSUE THREAD

**Issue by saiorama** [openai/plugins-quickstart#22]
I cloned this repo and followed the README to integrate this Quickstart plugin with ChatGPT. 

When I click on `Find Manifest File` after entering on the https://chat.openai.com/?model=gpt-4-plugins modal window, I get an error saying `Couldn't find manifest.`.

P.S. Tbh, where in the README it says `localhost:5003`, I had to use `http://0.0.0.0:5003` but that is a different documentation bug.

**Comment by Jimgitsit** [comment]
http://0.0.0.0:5003 doesn't work for me. I can open the manifest in my browser at http://0.0.0.0:5003/.well-known/ai-plugin.json. I've tried 127.0.0.1, localhost, http://0.0.0.0:5003/.well-known and http://0.0.0.0:5003/.well-known/ai-plugin.json. No bueno.

**Comment by saiorama** [comment]
@Jimgitsit if it helps, I'm using Safari on a Mac. 

In the end, I switched to `ngrok` to tunnel my local python server to a publicly visible https endpoint.

**Comment by yilmaznaslan** [comment]
I am having the same issue. Is there any solution other than ngrok ?

**Comment by gavrielc** [comment]
I had the same issue and was able to fix it by doing the following:

1. Use `localhost:5003`. 
2. You'll get an error "Failed to fetch localhost manifest. Check to ensure your localhost is running and your localhost server has CORS enabled."
3. Fix this error by following the instruction [here](https://github.com/openai/plugins-quickstart/issues/40) (remove the trailing comma in `ai-plugin.json` after `"url": "http://localhost:5003/openapi.yaml"`)

**Comment by yilmaznaslan** [comment]
Thanks @gavrielc  , that was it
