### ISSUE TITLE
Does anyone know how to receive user input parameters? 

### ISSUE THREAD

**Issue by wishtodaya** [openai/plugins-quickstart#28]
```
@app.get("/news/<string:url>")
async def get_news(url):
    print(url)
    return quart.Response(response=json.dumps(url), status=200)

```
I want to receive a URL link input from the user, how should I handle it?

**Comment by j4acks0n** [comment]
> ```
> @app.get("/news/<string:url>")
> async def get_news(url):
>     print(url)
>     return quart.Response(response=json.dumps(url), status=200)
> ```
> 
> I want to receive a URL link input from the user, how should I handle it?

Ummm I'm Not Sure Yet Maybe You Can Visit This
https://towardsdatascience.com/proper-ways-to-pass-environment-variables-in-json-for-curl-post-f797d2698bf3
Hope This Will Help

**Comment by logankilpatrick** [comment]
What you are doing above looks good!
