### ISSUE TITLE
Manifest has invalid JSON and prevents plugin from loading

### ISSUE THREAD

**Issue by areibman** [openai/plugins-quickstart#40]
## Description
The manifest file contains a trailing comma, so this is a malformed JSON. This creates a CORS error:
>Failed to fetch localhost manifest. Check to ensure your localhost is running and your localhost server has CORS enabled.

## Proposed fix
Format the JSON to remove this comma on line 12 of `ai-plugin.json`: `"url": "http://localhost:5003/openapi.yaml",`

New manifest:
```
{
    "schema_version": "v1",
    "name_for_human": "TODO Plugin (no auth)",
    "name_for_model": "todo",
    "description_for_human": "Plugin for managing a TODO list, you can add, remove and view your TODOs.",
    "description_for_model": "Plugin for managing a TODO list, you can add, remove and view your TODOs.",
    "auth": {
        "type": "none"
    },
    "api": {
        "type": "openapi",
        "url": "http://localhost:5003/openapi.yaml"
    },
    "logo_url": "http://localhost:5003/logo.png",
    "contact_email": "legal@example.com",
    "legal_info_url": "http://example.com/legal"
}
```
I've attached a PR that resolves this issue. #41

**Comment by areibman** [comment]
cc: @logankilpatrick

**Comment by logankilpatrick** [comment]
Fixed!
